# Generated by Django 2.2.3 on 2019-07-03 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', max_length=256),
        ),
        migrations.AddField(
            model_name='event',
            name='types',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_app.Event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation_status',
            field=models.IntegerField(choices=[('1', 'Available'), ('2', 'Reserved'), ('3', 'Paid')], default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(choices=[('1', 'Regular'), ('2', 'Premium'), ('3', 'VIP'), ('4', 'Reduced')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
